# We all gotta code here

# Approach
'''#########################################################################################################################################################################
1. Data Preprocessing: Extract the job descriptions from the provided job offer files and preprocess them by removing stop words, punctuations, and special characters.
   You can also perform stemming or lemmatization to reduce words to their base forms.

2. Feature Extraction: Extract the relevant features from the preprocessed job descriptions. For this task, you can use techniques such as bag-of-words, n-grams, and
   term frequency-inverse document frequency (TF-IDF).

3. Clustering: Use clustering algorithms such as K-means or Hierarchical clustering to group similar job descriptions based on th eir extracted features.

4. Summarization: Once the job descriptions have been clustered, summarize the requirements/pre-requisites that are common to each cluster. You can achieve this by
   identifying the most frequent terms or phrases within each cluster and constructing a summary of the requirements based on them.

5. Evaluation: Evaluate the effectiveness of your approach by comparing the summary generated by your system with the original job descriptions. You can use metrics
   such as precision, recall, and F1 score to measure the performance of your summarization system.
#############################################################################################################################################################################'''
import re

# First things first we gotta copy all the  stuff
with open('./Assets/eures_job_desc_en.txt', encoding='utf-8') as f:
    contents = f.readlines()

# Putting everything in a single string
delimiter = ' '
all_jobs_string = delimiter.join(contents)
print(all_jobs_string)

#Seperating all jobs and Printing apparently it's 10666
all_jobs_list = re.split(r'-----',all_jobs_string)

print(all_jobs_list)
print(type(all_jobs_list))
print(len(all_jobs_list))
print(all_jobs_list[:2])
